spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:${PORT_NUMBER}/${DATABASE_NAME}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true

  mail:
    host: smtp.gmail.com #SMTP 서버 호스트
    port: 587 #SMTP 서버 포트
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties:
      mail:
        smtp:
          auth: true # 사용자에 대한 인증 후 메일 전송
          connectiontimeout: 5000
          timeout: 5000
          starttls:
            enable: true
      auth-code-expiration-millis: 300000 #이메일 인증 코드 만료 시간: 5분

jwt:
  secret: ${JWT_SECRET_KEY}

profiles:
  active: local

file:
  upload-dir: uploads/