spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cammoa
    username: root
    password: 1234

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com #SMTP 서버 호스트
    port: 587 #SMTP 서버 포트
    username: rkdms10031013@gmail.com
    password: vhuy tyfe vznm exiv
    properties:
      mail:
        smtp:
          auth: true # 사용자에 대한 인증 후 메일 전송
          connectiontimeout: 5000
          timeout: 5000
          starttls:
            enable: true
      auth-code-expiration-millis: 300000 #이메일 인증 코드 만료 시간: 5분

jwt:
  secret: dGhpc2lzYXZlcnlzZWN1cmVhbmRsb25nc2VjcmV0a2V5dGhhdGlzb3ZlcjMyYnl0ZXM=

profiles:
  active: local

file:
  upload-dir: C:/cammoa/uploads/